on:
  workflow_dispatch:
jobs:
  test:
    name: test azurite table services
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: dotnet build
      - name: test
        run: dotnet test
