on:
  workflow_dispatch:
jobs:
  test:
    name: test azurite table services
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: dotnet build
      - name: run azurite
        run: start "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe"
      - name: test
        run: dotnet test
